# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'
platform :ios, '13.0'

target 'FirstProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Qdispatch
  
  pod 'SwiftyJSON'
  pod 'RealmSwift'
#  pod "SwiftUICardStack"
    pod 'AppRTC'
end
