# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Travel_Firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Travel_Firebase
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

end
