# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'
#platform :ios, '9.0'

target 'firebaseExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Qdispatch
  
  pod 'SwiftyJSON'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Database'
end
