# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipleaseV1' do
  # Comment the next line if you don't want to use dynamic frameworks


  use_frameworks!
  pod 'IQKeyboardManager'
  pod 'JGProgressHUD'
#  pod 'SwiftyJSON'

  pod  'Alamofire' ,  '~> 5.2'
end
