# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '001_Api_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 001_Api_SwiftUI
 pod 'Alamofire'
  pod 'SwiftyJSON'
end
